site_name: AI Month
remote_branch: gh-pages
site_url: https://template_site.acmbpdc.org
site_author: ACM BPDC
site_description: An overview of the AI Month; includes ML Essential sessions and the Kaggle competition
repo_url: https://github.com/acmbpdc/mkdocs-template
repo_name: acmbpdc/mkdocs-template

copyright: Copyright &copy; 2024 - ACM BITS Pilani Dubai Campus

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: assets/ACM_Logo.png
  favicon: assets/favicon.ico
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - header.autohide

extra:
  social:
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/acmbpdc
    - icon: fontawesome/brands/github 
      link: https://github.com/acmbpdc
    - icon: fontawesome/brands/discord
      link: https://discord.gg/DYQdxquYwP

# Use the below section for more specific control
nav:
  - Home: index.md
  - ML Essentials Tabular Datasets: './ML Essentials_ Exploring Data Analysis Techniques with Tabular Datasets.ipynb'
  - ML Essentials Computer Vision: './ML Essentials- Computer vision.ipynb'
  - ML Essentials NLP: './ML Essentials - NLP.ipynb'
  - Kaggle Konquest: './kaggle.md'

markdown_extensions:
  - toc:
      permalink: True

plugins:
  - search
  - mkdocs-jupyter